### PR TITLE
Bootstrap 4

### PR DESCRIPTION
**Pull request by dankimio**
- Bootstrap 4 support
- Transition from panels to regular forms
- Semantic HTML tags: use `h1` tags, wrap submit buttons in `form-group`
- Update code style to be consistent
- Update description and summary in gemspec
- Lock rake version
- Update README instructions

This should probably be merged into a separate branch until the final version of Bootstrap 4 is released.

### CODE REVIEW

**Comment by zedtux** [comment]
@hisea can you please check this PR and build a gem from it?

**Comment by hisea** [comment]
Bootstrap hasn't been released yet, I'm thinking to do a release bump of this gem when Bootstrap 4 is released.

For now, can we instead of merge into master, maybe  merge into a bootstrap_v4 branch and people can use it from the git branch?

thoughts @zedtux @dankimio ?

**Comment by hisea** [comment]
merged to bootstrap4 branch

**Comment by zedtux** [comment]
Agree with you @hisea but we could also build a gem following the Bootstrap versioning which is currently `4.0.0.alpha3.1`.
Actually, your gem should follow the bootstrap versioning so that the user can choose the right version of your gem for his version of bootstrap (I don't think the Devise versioning is important here, as I don't think they're changing the views so often, right?)

**Comment by dankimio** [comment]
We could also bump the version and build an alpha version of the gem (`v0.1.0.alpha1` or `v1.0.0.alpha1`) without following Bootstrap versioning, so there's at least some kind of release that includes Bootstrap 4 views.

**Comment by zedtux** [comment]
@dankimio what's the problem to follow the bootstrap versioning? It's gives clarity to developers. Don't  you like clarity? 😃

**Comment by dankimio** [comment]
@zedtux I don't know, it's up to @hisea to decide. Following Bootstrap versioning means we have to bump the version every time there's a new version, even if there aren't any changes. I don't think we should expect any significant changes in this gem if Bootstrap receives a minor or a patch update.

**Comment by hisea** [comment]
I'm not sure about following bootstrap versioning neither.

I agree with @dankimio on that irrelevant Bootstrap version bumps shouldn't prompt us for an additional build.

Also this gem both depends on Bootstrap and Devise. If follow Bootstrap versioning how about incompatible devise version upgrades. Could be more confusing.

**Comment by zedtux** [comment]
You're *just* moving the visibility issue somewhere else. I understand your point, but then how do you do to help developers to know which version they should use for their case?

In any cases, it's obviously your choice @hisea, and I just want a packages version I can use in my project 😃.
I just addressed an issue with the visibility on compatibilities with Bootstrap (from my point of view, this gem is bringing Bootstrap to Devise's views, not Devises to Bootstrap, and _ Following Bootstrap versioning_ is not a rule you must follow, it's a suggestion so that you bump the version only when it make sens).

**Comment by hisea** [comment]
just built and released version `1.0.0.alpha1` based of the `bootstrap4` branch.

Thanks again for your contribution @dankimio

**Comment by shardulmohite** [comment]
Bootstrap 4 is released, any plans to release this also?

**Comment by TheMissingNTLDR** [comment]
@shardulmohite - Currently I use this in my gemfile and it works:
`gem 'devise-bootstrap-views', :git => 'https://github.com/hisea/devise-bootstrap-views.git', :branch => 'bootstrap4'`

**Pull request merged**
